services:
  - type: web
    name: atomberg-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_hWAn8RQK7VPf@ep-delicate-moon-aonib0iy-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: JWT_SECRET
        generateValue: true
      - key: LIVEKIT_API_KEY
        value: devkey
      - key: LIVEKIT_API_SECRET
        value: secret
      - key: LIVEKIT_WS_URL
        value: ws://localhost:7880
      - key: REDIS_URL
        value: rediss://default:gQAAAAAAAc6ZAAIgcDJhOTZhYTNhMjg3ZmE0ZjU2ODg3MzliNTE3MWUzNjg3MQ@knowing-deer-118425.upstash.io:6379
      - key: MINIO_ENDPOINT
        value: localhost
      - key: MINIO_PORT
        value: 9000
      - key: MINIO_ACCESS_KEY
        value: minioadmin
      - key: MINIO_SECRET_KEY
        value: minioadmin
      - key: MINIO_BUCKET
        value: atomberg
      - key: UPLOAD_DIR
        value: ./uploads
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /
